IF
	HitBy([ANYONE],ELECTRICITY)
THEN
	RESPONSE #100	
		ReallyForceSpellRes("pxkribi2",Myself)
END

IF
	Heard([ANYONE],111)
THEN
	RESPONSE #100
		MoveToObject(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(Nearestenemyof(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(Nearestenemyof(Myself),30)
END

IF
  ActionListEmpty()
  AttackedBy([0],DEFAULT)
THEN
  RESPONSE #100
    Attack(Lastattackerof(Myself))
END

